# Generated by Django 2.2.9 on 2020-03-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderInfo',
            new_name='SliderInfos',
        ),
    ]
