# Generated by Django 2.2.9 on 2020-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0002_auto_20200314_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=150, unique=True)),
                ('slider_details', models.TextField(blank=True, null=True)),
                ('slider_img', models.ImageField(blank=True, upload_to='slider')),
                ('ordering', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SliderInfos',
        ),
    ]
