# Generated by Django 2.2.9 on 2020-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0004_auto_20200314_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='latest_news',
            field=models.BooleanField(default=False),
        ),
    ]
