# Generated by Django 2.2.9 on 2020-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0006_productinfo_overview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='test_battery_life',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='test_camera',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='test_display',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='test_performance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
