# Generated by Django 2.2.9 on 2020-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0007_auto_20200315_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='main_cam_type_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
