# Generated by Django 2.2.9 on 2020-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0008_productinfo_main_cam_type_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='selfie_cam_type_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
