# Generated by Django 2.2.9 on 2020-03-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0010_auto_20200317_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='sound_3_5mm_jack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='sound_loudspeaker',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
