# Generated by Django 2.2.9 on 2020-03-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0012_categoryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinfo',
            name='cat_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
