# Generated by Django 2.2.9 on 2020-03-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0013_categoryinfo_cat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmapp.CategoryInfo'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmapp.CategoryInfo'),
        ),
    ]
