# Generated by Django 3.0.4 on 2020-03-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0015_auto_20200318_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThreeDView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_d_img', models.ImageField(blank=True, upload_to='product_3d_view')),
                ('ordering', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmapp.ProductInfo')),
            ],
        ),
    ]
