# Generated by Django 3.0.4 on 2020-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0016_productthreedview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productthreedview',
            name='ordering1',
            field=models.IntegerField(default=0),
        ),
    ]
