# Generated by Django 3.0.4 on 2020-03-27 08:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0017_productthreedview_ordering1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productthreedview',
            name='ordering1',
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_video', models.TextField(blank=True, null=True)),
                ('review_details', ckeditor.fields.RichTextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmapp.ProductInfo')),
            ],
        ),
    ]
