# Generated by Django 3.0.4 on 2020-03-31 04:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0018_auto_20200327_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='use_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
