# Generated by Django 3.0.4 on 2020-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0019_auto_20200331_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
