# Generated by Django 3.0.4 on 2020-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0020_brandinfo_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='short_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
