# Generated by Django 3.0.4 on 2020-04-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0021_auto_20200331_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_title', models.CharField(blank=True, max_length=200, null=True)),
                ('site_image', models.ImageField(blank=True, null=True, upload_to='product_pricing')),
                ('site_link', models.TextField(blank=True, null=True)),
                ('dollar_price', models.FloatField(default=0)),
                ('euro_price', models.FloatField(default=0)),
                ('rupee_price', models.FloatField(default=0)),
                ('bd_price', models.FloatField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmapp.ProductInfo')),
            ],
        ),
    ]
