# Generated by Django 3.0.4 on 2020-04-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0022_productpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
