# Generated by Django 3.0.4 on 2020-04-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0023_productinfo_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.CharField(max_length=150, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('user_email', models.CharField(blank=True, max_length=150, null=True)),
                ('user_comment', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('blog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsmapp.BlogInfo')),
            ],
        ),
    ]
