# Generated by Django 3.0.4 on 2020-04-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0024_auto_20200408_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWiseUserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('user_email', models.CharField(blank=True, max_length=150, null=True)),
                ('user_comment', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsmapp.ProductInfo')),
            ],
        ),
    ]
