# Generated by Django 3.0.4 on 2020-06-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0026_auto_20200414_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='blog_slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
