# Generated by Django 3.0.4 on 2020-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0027_auto_20200620_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
