# Generated by Django 2.2.9 on 2020-10-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0029_auto_20200717_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPermalink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info_type', models.CharField(max_length=150)),
                ('permalink', models.CharField(max_length=150)),
                ('redirect_url', models.CharField(max_length=255)),
            ],
        ),
    ]
