# Generated by Django 2.2.9 on 2020-10-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0030_productpermalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpermalink',
            name='content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmapp.CategoryInfo'),
        ),
    ]
