# Generated by Django 2.2.9 on 2020-10-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0031_productpermalink_content_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpermalink',
            old_name='content_id',
            new_name='content',
        ),
    ]
