# Generated by Django 2.2.9 on 2020-10-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmapp', '0035_auto_20201012_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpermalink',
            name='content',
            field=models.IntegerField(default=0),
        ),
    ]
